### PR TITLE
Change editor to CKEditor and add Mathjax support

### LINKED ISSUE #62: Writing LaTeX-like Mathematical Equations on Problem Description
A support for making mathematical equations using LaTeX-like syntaxes would be appreciated. One of the library that might support it is [MathJax](https://www.mathjax.org/).

### PR DESCRIPTION
**Pull request by mamat-rahmat**
Fixes #62.

### CODE REVIEW

**Review by fushar — CHANGES_REQUESTED** [review]
You will also need to update `publish.sh`.

**Comment by mamat-rahmat** [comment]
@fushar release archive size increases from 16.5 MB to 23.3 MB. What do you think?
I believe there is some folder that can be ignored. But maybe i need some time to figure it out.

**Comment by fushar** [comment]
Yes, please echo back when you think you've ignored everything possible.

**Comment by fushar** [comment]
Closing this due to lack of activity.

**Comment by fushar** [comment]
Giving up on this, as the font sizes are too large. Maybe it is not worth it for now.

**Pull request closed without merging**
